---

- name: Указываем часовой пояс (Московское время)
  ansible.builtin.copy:
    src: /usr/share/zoneinfo/Europe/Moscow
    dest: /etc/localtime

- name: Restart chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted