---
- name: Отрыть порт TCP 60 в /etc/audit/auditd.conf
  ansible.builtin.replace:
    path: /etc/audit/auditd.conf
    regexp: '##tcp_listen_port = 60'
    replace: 'tcp_listen_port = 60'

- name: Restart auditd
  command: /sbin/service auditd restart
