- hosts: log 
  become: yes
  become_user: root
  
  roles:
      - time
      - audit-server

- hosts: web
  become: yes
  become_user: root
  
  roles:
      - time
      - nginx
      - audit-client
  
  vars_files:
    - vars.yml

  

   
