---
- name: Раскоментируем строки rsyslog.conf
  replace:
    dest: /etc/rsyslog.conf
    regexp: '#$ModLoad imudp'
    replace: '$ModLoad imudp'

- name: Раскоментируем строки rsyslog.conf
  replace:
    dest: /etc/rsyslog.conf
    regexp: '#$UDPServerRun 514'
    replace: '$UDPServerRun 514'

- name: Раскоментируем строки rsyslog.conf
  replace:
    dest: /etc/rsyslog.conf
    regexp: '#$ModLoad imtcp'
    replace: '$ModLoad imtcp'

- name: Раскоментируем строки rsyslog.conf
  replace:
    dest: /etc/rsyslog.conf
    regexp: '#$InputTCPServerRun 514'
    replace: '$InputTCPServerRun 514'

- name: Добавляем строки
  ansible.builtin.blockinfile:
    path: /etc/rsyslog.conf
    block: |
      #Add remote logs
      $template RemoteLogs,"/var/log/rsyslog/%HOSTNAME%/%PROGRAMNAME%.log"
      *.* ?RemoteLogs
      & ~
  notify: Restart rsyslog